<?php
if (isset($_SESSION['user']['students_id'])) {
    header('Location: ./dashboard.php?page=classroom');
    exit;
}

$error = $_SESSION['error'] ?? null;
unset($_SESSION['error']);

?>
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Buat Akun Siswa</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="./dashboard.php">Dashboard</a></li>
                    <li class="breadcrumb-item active">Buat Akun Siswa</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Buat Akun Siswa</h3>
                    </div>
                    <form action="./app/controllers/StudentController.php" method="POST">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="nama_lengkap">Nama Lengkap</label>
                                        <input type="text" class="form-control <?= isset($error['nama_lengkap']) ? 'is-invalid' : '' ?>" id="nama_lengkap" name="nama_lengkap"
                                               value="<?= $error ? $error['old']['nama_lengkap'] : '' ?>" placeholder="Masukkan nama lengkap">
                                        <?= isset($error['nama_lengkap']) ? '<div class="invalid-feedback">' . $error['nama_lengkap'] . '</div>' : '' ?>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="nis">NIS Siswa</label>
                                        <input type="text" class="form-control" placeholder="Generated by system" readonly>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label for="jenis_kelamin">Jenis kelamin</label>
                                            <select class="form-control <?= isset($error['jenis_kelamin']) ? 'is-invalid' : '' ?>" id="jenis_kelamin" name="jenis_kelamin">
                                                <option value="Laki-Laki">Laki-Laki</option>
                                                <option value="Perempuan">Perempuan</option>
                                            </select>
                                            <?= isset($error['jenis_kelamin']) ? '<div class="invalid-feedback">' . $error['jenis_kelamin'] . '</div>' : '' ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="agama">Agama</label>
                                        <input type="text" class="form-control <?= isset($error['agama']) ? 'is-invalid' : '' ?>" id="agama" name="agama"
                                               value="<?= $error ? $error['old']['agama'] : '' ?>" placeholder="Masukkan agama">
                                        <?= isset($error['agama']) ? '<div class="invalid-feedback">' . $error['agama'] . '</div>' : '' ?>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="tempat_lahir">Tempat Lahir</label>
                                        <input type="text" class="form-control <?= isset($error['tempat_lahir']) ? 'is-invalid' : '' ?>" id="tempat_lahir" name="tempat_lahir"
                                               value="<?= $error ? $error['old']['tempat_lahir'] : '' ?>" placeholder="Masukkan tempat lahir">
                                        <?= isset($error['tempat_lahir']) ? '<div class="invalid-feedback">' . $error['tempat_lahir'] . '</div>' : '' ?>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Tanggal Lahir</label>
                                        <div class="input-group">
                                            <input type="text" class="form-control <?= isset($error['tanggal_lahir']) ? 'is-invalid' : '' ?>" data-inputmask-alias="datetime" data-inputmask-inputformat="yyyy/mm/dd"
                                                   data-mask="" inputmode="numeric" id="tanggal_lahir" name="tanggal_lahir" placeholder="yyyy/mm/dd"
                                                   value="<?= $error ? $error['old']['tanggal_lahir'] : '' ?>">
                                            <?= isset($error['tanggal_lahir']) ? '<div class="invalid-feedback">' . $error['tanggal_lahir'] . '</div>' : '' ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="alamat">Alamat</label>
                                        <input type="text" class="form-control <?= isset($error['alamat']) ? 'is-invalid' : '' ?>" id="alamat" name="alamat"
                                               value="<?= $error ? $error['old']['alamat'] : '' ?>" placeholder="Masukkan alamat">
                                        <?= isset($error['alamat']) ? '<div class="invalid-feedback">' . $error['alamat'] . '</div>' : '' ?>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="no_hp">No HP</label>
                                        <input type="text" class="form-control <?= isset($error['no_hp']) ? 'is-invalid' : '' ?>" id="no_hp" name="no_hp"
                                               value="<?= $error ? $error['old']['no_hp'] : '+62 ' ?>" placeholder="Masukkan nama lengkap">
                                        <?= isset($error['no_hp']) ? '<div class="invalid-feedback">' . $error['no_hp'] . '</div>' : '' ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" name="submit" value="create" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>