<?php
require_once './app/models/Student.php';
require_once './app/helpers/Alert.php';

$student = new Student();
$authId = $_SESSION['user']['id'] ?? null;
$authStudentId = $_SESSION['user']['students_id'] ?? null;
$student = $student->getStudentProfile($authStudentId);

$error = $_SESSION['error'] ?? null;
unset($_SESSION['error']);

if (!$authStudentId) {
    header('Location: ./dashboard.php?page=create-student');
    exit();
}
?>

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Student</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="./dashboard.php">Dashboard</a></li>
                    <li class="breadcrumb-item active">Student Settings</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <?php Alert::notify(); ?>
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Ubah Akun Siswa</h3>
                    </div>
                    <form action="./app/controllers/StudentController.php" method="POST">
                        <div class="card-body">
                            <div class="row">
                                <input type="hidden" name="id" value="<?= $student['id'] ?>">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="nama_lengkap">Nama Lengkap</label>
                                        <input type="text" class="form-control <?= isset($error['nama_lengkap']) ? 'is-invalid' : '' ?>" id="nama_lengkap" name="nama_lengkap"
                                               value="<?= $student['fullname'] ?>" placeholder="Masukkan nama lengkap">
                                        <?= isset($error['nama_lengkap']) ? '<div class="invalid-feedback">' . $error['nama_lengkap'] . '</div>' : '' ?>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="nis">NIS Siswa</label>
                                        <input type="text" class="form-control" value="<?= $student['nis'] ?>" placeholder="Generated by system" readonly>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label for="jenis_kelamin">Jenis kelamin</label>
                                            <select class="form-control <?= isset($error['jenis_kelamin']) ? 'is-invalid' : '' ?>" id="jenis_kelamin" name="jenis_kelamin">
                                                <option value="Laki-Laki" <?= $student['gender'] === 'Laki-Laki' ? 'selected' : '' ?>>Laki-Laki</option>
                                                <option value="Perempuan" <?= $student['gender'] === 'Perempuan' ? 'selected' : '' ?>>Perempuan</option>
                                            </select>
                                            <?= isset($error['jenis_kelamin']) ? '<div class="invalid-feedback">' . $error['jenis_kelamin'] . '</div>' : '' ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="agama">Agama</label>
                                        <input type="text" class="form-control <?= isset($error['agama']) ? 'is-invalid' : '' ?>" id="agama" name="agama"
                                               value="<?= $student['religion'] ?>" placeholder="Masukkan agama">
                                        <?= isset($error['agama']) ? '<div class="invalid-feedback">' . $error['agama'] . '</div>' : '' ?>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="tempat_lahir">Tempat Lahir</label>
                                        <input type="text" class="form-control <?= isset($error['tempat_lahir']) ? 'is-invalid' : '' ?>" id="tempat_lahir" name="tempat_lahir"
                                               value="<?= $student['birthplace'] ?>" placeholder="Masukkan tempat lahir">
                                        <?= isset($error['tempat_lahir']) ? '<div class="invalid-feedback">' . $error['tempat_lahir'] . '</div>' : '' ?>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Tanggal Lahir</label>
                                        <div class="input-group">
                                            <input type="text" class="form-control <?= isset($error['tanggal_lahir']) ? 'is-invalid' : '' ?>" data-inputmask-alias="datetime" data-inputmask-inputformat="yyyy/mm/dd"
                                                   data-mask="" inputmode="numeric" id="tanggal_lahir" name="tanggal_lahir" placeholder="yyyy/mm/dd"
                                                   value="<?= $student['birthdate'] ?>">
                                            <?= isset($error['tanggal_lahir']) ? '<div class="invalid-feedback">' . $error['tanggal_lahir'] . '</div>' : '' ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="alamat">Alamat</label>
                                        <input type="text" class="form-control <?= isset($error['alamat']) ? 'is-invalid' : '' ?>" id="alamat" name="alamat"
                                               value="<?= $student['address'] ?>" placeholder="Masukkan alamat">
                                        <?= isset($error['alamat']) ? '<div class="invalid-feedback">' . $error['alamat'] . '</div>' : '' ?>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="no_hp">No HP</label>
                                        <input type="text" class="form-control <?= isset($error['no_hp']) ? 'is-invalid' : '' ?>" id="no_hp" name="no_hp"
                                               value="<?= $student['phone_number'] ?>" placeholder="Masukkan nama lengkap">
                                        <?= isset($error['no_hp']) ? '<div class="invalid-feedback">' . $error['no_hp'] . '</div>' : '' ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" name="submit" value="update" class="btn btn-primary">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

